### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by parkerlreed** [BigfootACA/systemd-gadget#1]
Any instructions for starting this? 

I see that the gadget start service has to launch but if I run gadget start and then for example the geth service, nothing comes up network wise.

**Comment by parkerlreed** [comment]
Think I figured out my issue. The way I have it installed (using it on a Steam Deck), the files don't get populated to the file system fast enough because they are on an overlay. So I have to restart the gadget start service after I get into the system. Currently logged into the Deck via USB serial!

**Comment by BigfootACA** [comment]
you can check if there is anything under the `/sys/class/udc` folder.
